  blank_issues_enabled: false
  contact_links:
  - name: Problems with Spotify (spicetify-cli) integration?
    url: https://github.com/khanhas/spicetify-cli/issues
    about: Please visit the spicetify-cli repo to report issues & help about the Spotify integration.

